title: TzZek
description: A techie and cybersecurity tinkerer. Join me on this sporadic adventure.
lang: en-US
timezone: Asia/Jakarta
image: FullBlurOpt.jpg
repo: 'https://github.com/piharpi/jekyll-klise'
mode: dark
author:
  name: TzZek
  bio: Welcome to my blog. I hope you find something useful!
  username: TzZek
  github: TzZek
  twitter: TzZek
  facebook: facebook_username
  email: scapers-begon@
  avatar: zekhat.png
url: 'https://tzzek.com'
baseurl: null
permalink: '/:title/'
google_analytics: null
fb_appid: null
collections:
  posts:
    output: true
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
defaults:
  - scope:
      path: ''
    values:
      layout: post
      comments: false
jekyll_compose:
  post_default_front_matter:
    modified: null
    tags: []
    description: null
  draft_default_front_matter:
    modified: null
    tags: []
    description: null
number_of_posts: 6
sass:
  style: compressed
include:
  - _redirects
  - .htaccess
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
